In [2]:
import pandas as pd

C:\Users\ahska\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [4]:
# Load the dataset
file_path = 'C:/Users/ahska/Documents/Ahska/UCL/3 - Final Project (Dissertation)/Dissertation 2/redfin_seattle_dataset.csv'
data = pd.read_csv(file_path)

# Display the first few rows and the summary information of the dataset
data_head = data.head()
data_info = data.info()
data_description = data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17494 entries, 0 to 17493
Data columns (total 27 columns):
 #   Column                                                                                       Non-Null Count  Dtype
---  ------                                                                                       --------------  -----
 0   SALE TYPE                                                                                    17494 non-null  object
 1   SOLD DATE                                                                                    14056 non-null  object
 2   PROPERTY TYPE                                                                                17494 non-null  object
 3   ADDRESS                                                                                      17480 non-null  object
 4   CITY                                                                                         17485 non-null  object
 5   STATE OR PROVINCE                                                                            17494 non-null  object
 6   ZIP OR POSTAL CODE                                                                           17488 non-null  float64
 7   PRICE                                                                                        17492 non-null  float64
 8   BEDS                                                                                         17007 non-null  float64
 9   BATHS                                                                                        16942 non-null  float64
 10  LOCATION                                                                                     16197 non-null  object
 11  SQUARE FEET                                                                                  17080 non-null  float64
 12  LOT SIZE                                                                                     14488 non-null  float64
 13  YEAR BUILT                                                                                   16986 non-null  float64
 14  DAYS ON MARKET                                                                               2766 non-null   float64
 15  $/SQUARE FEET                                                                                17077 non-null  float64
 16  HOA/MONTH                                                                                    4784 non-null   float64
 17  STATUS                                                                                       16204 non-null  object
 18  NEXT OPEN HOUSE START TIME                                                                   370 non-null    object
 19  NEXT OPEN HOUSE END TIME                                                                     370 non-null    object
 20  URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)  17494 non-null  object
 21  SOURCE                                                                                       16204 non-null  object
 22  MLS#                                                                                         16204 non-null  object
 23  FAVORITE                                                                                     17494 non-null  object
 24  INTERESTED                                                                                   17494 non-null  object
 25  LATITUDE                                                                                     17494 non-null  float64
 26  LONGITUDE                                                                                    17494 non-null  float64
dtypes: float64(12), object(15)
memory usage: 3.6+ MB

In [7]:
# Displaying the dataset
data_head

,SALE TYPE,SOLD DATE,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,...,STATUS,NEXT OPEN HOUSE START TIME,NEXT OPEN HOUSE END TIME,URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING),SOURCE,MLS#,FAVORITE,INTERESTED,LATITUDE,LONGITUDE
0,PAST SALE,September-7-2022,Townhouse,928 NW 51st St Unit B,Seattle,WA,98107.0,865000.0,3.0,2.0,...,Sold,NaN,NaN,https://www.redfin.com/WA/Seattle/928-NW-51st-...,NWMLS as Distributed by MLS Grid,1976461.0,N,Y,47.665890,-122.369911
1,PAST SALE,November-9-2022,Townhouse,1316 NW 67th St,Seattle,WA,98117.0,1111000.0,3.0,2.5,...,Sold,NaN,NaN,https://www.redfin.com/WA/Seattle/1316-NW-67th...,NWMLS as Distributed by MLS Grid,1986603.0,N,Y,47.677965,-122.373688
2,PAST SALE,April-28-2023,Townhouse,2048 NW 61st St Unit A,Seattle,WA,98107.0,870000.0,3.0,2.0,...,Sold,NaN,NaN,https://www.redfin.com/WA/Seattle/2048-NW-61st...,NWMLS as Distributed by MLS Grid,2049229.0,N,Y,47.673297,-122.384359
3,PAST SALE,October-31-2022,Single Family Residential,7310 19th Ave NW,Seattle,WA,98117.0,890000.0,3.0,2.0,...,Sold,NaN,NaN,https://www.redfin.com/WA/Seattle/7310-19th-Av...,NWMLS as Distributed by MLS Grid,2006504.0,N,Y,47.681702,-122.380777
4,PAST SALE,October-14-2022,Single Family Residential,924 NW 64th St,Seattle,WA,98107.0,1000000.0,2.0,2.0,...,Sold,NaN,NaN,https://www.redfin.com/WA/Seattle/924-NW-64th-...,NWMLS as Distributed by MLS Grid,1995102.0,N,Y,47.675493,-122.369847

In [6]:
# Descripting the dataset
data_description

,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,SQUARE FEET,LOT SIZE,YEAR BUILT,DAYS ON MARKET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE
count,17488.000000,1.749200e+04,17007.000000,16942.000000,17080.000000,14488.000000,16986.000000,2766.000000,1.707700e+04,4784.000000,17494.000000,17494.000000
mean,98114.787683,1.194777e+06,3.027577,2.411079,1955.638934,7177.031543,1972.335158,46.744758,1.058005e+03,432.077968,47.622624,-122.324598
std,216.980905,1.663211e+06,1.441845,19.684771,1787.234002,14530.362045,38.121539,77.122743,2.222549e+04,426.333525,0.071019,0.050482
min,69813.000000,1.399900e+04,0.000000,0.500000,0.000000,1.000000,1889.000000,1.000000,1.900000e+01,0.000000,47.493453,-122.418930
25%,98106.000000,6.420000e+05,2.000000,1.500000,1151.000000,3000.000000,1942.000000,7.000000,4.550000e+02,78.750000,47.558885,-122.365355
50%,98117.000000,8.599500e+05,3.000000,2.000000,1690.000000,5123.500000,1971.000000,23.000000,5.600000e+02,384.000000,47.633262,-122.327354
75%,98126.000000,1.285000e+06,4.000000,3.000000,2430.000000,7641.000000,2008.000000,57.000000,6.800000e+02,607.000000,47.683611,-122.289447
max,98416.000000,7.000000e+07,48.000000,2560.000000,156296.000000,493925.000000,2025.000000,1473.000000,1.400000e+06,4699.000000,47.739677,-122.211352

In [8]:
# Convert 'SOLD DATE' to datetime format
data['SOLD DATE'] = pd.to_datetime(data['SOLD DATE'], errors='coerce')

In [14]:
# Count the number of houses for each property type meeting either condition
property_type = data['PROPERTY TYPE'].value_counts()

# Display results
print("\nNumber of houses for each property type with (BEDS or BATHS):")
print(property_type)

Number of houses for each property type with (BEDS or BATHS):
PROPERTY TYPE
Single Family Residential    10694
Condo/Co-op                   3289
Townhouse                     2692
Vacant Land                    367
Multi-Family (2-4 Unit)        224
Multi-Family (5+ Unit)         105
Other                           75
Moorage                         25
Mobile/Manufactured Home        22
Parking                          1
Name: count, dtype: int64

In [10]:
# Display counts of Houses with 0 and blank (NaN) 'BEDS'
beds_zero = data[data['BEDS'] == 0].shape[0]
beds_nan = data['BEDS'].isna().sum()

# Display counts of Houses with 0, 0.5, and blank (NaN) 'BATHS'
baths_zero = data[data['BATHS'] == 0].shape[0]
baths_half = data[data['BATHS'] == 0.5].shape[0]
baths_nan = data['BATHS'].isna().sum()

print("Number of Houses with 0 Beds:", beds_zero)
print("Number of Houses with blank Beds:", beds_nan)
print("Number of Houses with 0 Baths:", baths_zero)
print("Number of Houses with 0.5 Baths:", baths_half)
print("Number of Houses with blank Baths:", baths_nan)

Number of Houses with 0 Beds: 195
Number of Houses with blank Beds: 487
Number of Houses with 0 Baths: 0
Number of Houses with 0.5 Baths: 9
Number of Houses with blank Baths: 552

In [13]:
# Identify houses with 0 or NaN 'BEDS'
beds_zero_or_nan = data[(data['BEDS'] == 0) | (data['BEDS'].isna())]

# Identify houses with 0, 0.5, or NaN 'BATHS'
baths_zero_half_or_nan = data[(data['BATHS'] == 0) | (data['BATHS'] == 0.5) | (data['BATHS'].isna())]

# Combine the filters for BEDS and BATHS
combined_filter = data[(data['BEDS'] == 0) | (data['BEDS'].isna()) |
                       (data['BATHS'] == 0) | (data['BATHS'] == 0.5) | (data['BATHS'].isna())]

# Count the number of houses for each property type meeting the BEDS condition
beds_counts = beds_zero_or_nan['PROPERTY TYPE'].value_counts()

# Count the number of houses for each property type meeting the BATHS condition
baths_counts = baths_zero_half_or_nan['PROPERTY TYPE'].value_counts()

# Count the number of houses for each property type meeting either condition
combined_counts = combined_filter['PROPERTY TYPE'].value_counts()

# Display results
print("Number of houses for each property type with 0 or NaN BEDS:")
print(beds_counts)
print("\nNumber of houses for each property type with 0, 0.5, or NaN BATHS:")
print(baths_counts)
print("\nNumber of houses for each property type with either condition (BEDS or BATHS):")
print(combined_counts)

Number of houses for each property type with 0 or NaN BEDS:
PROPERTY TYPE
Vacant Land                  367
Condo/Co-op                  151
Single Family Residential     68
Multi-Family (5+ Unit)        36
Moorage                       24
Multi-Family (2-4 Unit)       22
Other                          6
Townhouse                      5
Mobile/Manufactured Home       2
Parking                        1
Name: count, dtype: int64

Number of houses for each property type with 0, 0.5, or NaN BATHS:
PROPERTY TYPE
Vacant Land                  367
Single Family Residential     75
Multi-Family (5+ Unit)        38
Moorage                       25
Multi-Family (2-4 Unit)       22
Condo/Co-op                   21
Townhouse                      6
Other                          4
Mobile/Manufactured Home       2
Parking                        1
Name: count, dtype: int64

Number of houses for each property type with either condition (BEDS or BATHS):
PROPERTY TYPE
Vacant Land                  367
Condo/Co-op                  153
Single Family Residential     76
Multi-Family (5+ Unit)        38
Moorage                       25
Multi-Family (2-4 Unit)       22
Townhouse                      6
Other                          6
Mobile/Manufactured Home       2
Parking                        1
Name: count, dtype: int64